version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  
  backend:
    build: ./backend
    container_name: backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5050
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=example
    
  redis:
    image: redis
    container_name: redis
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
volumes:
  database: