
version: '3.8'

services:
  frontend:
    build: frontend/
    ports:
      - 5050:5050
    container_name: frontend

  backend:
    build: backend/
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data