version: '3.8'

services:
  frontend:
    build: Frontend/
    ports:
      - 5050:5050
    container_name: frontend

  backend:
    build: Backend/
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    container_name: redis
